# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "github-actions"
    # Workflow files stored in the default location of `.github/workflows`
    # You don't need to specify `/.github/workflows` for `directory`. You can use `directory: "/"`.
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"
    labels:
      - dependencies
    commit-message:
      prefix: "chore(deps)"
    open-pull-requests-limit: 5
  - package-ecosystem: "pip"
    # Python dependencies are defined in `pyproject.toml` and `requirements.txt` at the repository root.
    directory: "/" # Location of Python package manifests
    schedule:
      interval: "weekly"
    labels:
      - dependencies
    commit-message:
      prefix: "chore(deps)"
    open-pull-requests-limit: 5
  - package-ecosystem: "devcontainers"
    directory: "/.devcontainer"
    schedule:
      interval: "weekly"
    labels:
      - dependencies
    commit-message:
      prefix: "chore(deps)"
    open-pull-requests-limit: 5
